r"""
Emit LaTeX table bodies from results/*.json.
============================================

Companion to figures_paper.py. Together they close the hand-transcription loop
that produced defects C1-C7: until now every number reached the manuscript as
stdout -> a script docstring -> a LaTeX literal, with no link back to the run
that measured it.

Each emitter writes paper_cnsns/tables/<name>.tex containing ONLY the rows, so
the manuscript keeps its own caption, label and column spec and can be edited
freely without this script clobbering it. Include with \input{tables/<name>}.

A table whose JSON is missing is reported and skipped, never emitted from stale
numbers.
"""
import json, os, sys

OUT = os.path.join("paper_cnsns", "tables")
EOL = r" \\"          # LaTeX row terminator


def _load(name):
    """Return the payload; resultio.dump wraps it under "payload" with provenance."""
    with open(os.path.join("results", name + ".json")) as fh:
        d = json.load(fh)
    return d.get("payload", d)


def _sha(name):
    with open(os.path.join("results", name + ".json")) as fh:
        return json.load(fh).get("git_sha", "?")[:8]


def _write(name, rows, note):
    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, name + ".tex")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("%% GENERATED by make_tables.py -- do not edit by hand.\n")
        fh.write("%% source: " + note + "\n")
        fh.write("\n".join(rows) + "\n")
    print("  wrote " + path)


def table_nconv():
    """Table 2: dimension scaling of the forward operator."""
    d = _load("n_convergence")
    nseed = len(d["rows"][0].get("solves", [])) or "?"
    rows = [r"%-3d & $%.1f\pm%.1f$ & $%.1f$ & $%.1e$" % (
                r_["n"], r_["solve_mean"], r_["solve_std"], r_["lift"],
                50.0 ** (r_["n"] + 1)) + EOL
            for r_ in d["rows"]]
    _write("nconv", rows, "results/n_convergence.json (%s seeds), git %s"
           % (nseed, _sha("n_convergence")))


def table_mcquality():
    """Table T-new1: is the Monte Carlo reference precise enough? (R1.2)

    Paired SE at the published 200k budget; the naive i.i.d. figure the code used
    to report, which overstates it; the SE at the 1M budget the revision adopts;
    the common-random-numbers bound on Euler bias at 400 steps; and the published
    solve-error after de-noising.
    """
    d = _load("mc_quality")
    by_n = {r["n"]: r for r in d["statistical"]}
    nan = float("nan")
    rows = []
    for h in d["headline"]:
        r = by_n.get(h["n"], {})
        # the statistical block stores SEs in price units; the table is in px bp
        rows.append(r"%-3d & $%.2f$ & $%.2f$ & $%.2f$ & $%.2f$ & $%.1f$ & $%.1f$" % (
            h["n"], 1e4 * r.get("rms_se_200k", nan),
            1e4 * r.get("rms_se_200k_naive", nan), 1e4 * r.get("rms_se_1m", nan),
            h["euler_bias_400_px_bp"], h["published"], h["denoised"]) + EOL)
    _write("mcquality", rows, "results/mc_quality.json, git " + _sha("mc_quality"))


def table_arbitrage():
    """Table T-new3: static-arbitrage counts on market, model and liquid core.

    The point is R1.6: if the filtered surface is arbitrage-free then the 496
    vol bp fit is a statement about the model, not about the data.
    """
    d = _load("arbitrage")
    rows = []
    for key, label in [("market", "Market surface"),
                       ("model", "Calibrated model surface"),
                       ("liquid_core", r"Liquid core ($|k|\le0.10$)")]:
        s = d.get(key)
        if not s or "butterfly" not in s:
            continue
        rows.append(r"%s & %d/%d & %d/%d & %d/%d & $%+.2f$" % (
            label,
            s["butterfly"]["n_violations"], s["butterfly"]["n_tested"],
            s["vertical"]["n_violations"], s["vertical"]["n_tested"],
            s["calendar"]["n_violations"], s["calendar"]["n_tested"],
            s["butterfly"]["worst_px_bp"]) + EOL)
    if not rows:
        raise KeyError("market/model/liquid_core")
    q = d["data_quality"]
    rows.append(r"\midrule")
    rows.append(r"\multicolumn{5}{@{}l}{%d raw instruments filtered to %d fitted "
                r"points: %d two-sided, %d mark-price fallback, %d zero volume.}"
                % (q["n_raw_instruments"], q["n_fitted"], q["n_two_sided"],
                   q["n_mark_fallback"], q["n_zero_volume"]) + EOL)
    _write("arbitrage", rows, "results/arbitrage.json, git " + _sha("arbitrage"))


def table_regime():
    """Table: Hurst exponent by market regime, pre- and post-ETF. (R1.5)"""
    d = _load("regime_hurst")
    s = d["summary"]
    rows = [r"Pre-ETF (2023) & %d & $%.4f$ & $%.4f$ & $%.4f$" % (
                s["pre"]["n"], s["pre"]["H_mean"], s["pre"]["H_sd"],
                s["pre"]["H_median"]) + EOL,
            r"Post-ETF (2024) & %d & $%.4f$ & $%.4f$ & $%.4f$" % (
                s["post"]["n"], s["post"]["H_mean"], s["post"]["H_sd"],
                s["post"]["H_median"]) + EOL,
            r"\midrule",
            r"\multicolumn{5}{@{}l}{Difference $%+.4f$; Welch $p=%.3f$; "
            r"Mann--Whitney $p=%.3f$;}" % (
                s["diff"], s["welch_p"], s["mannwhitney_p"]) + EOL,
            r"\multicolumn{5}{@{}l}{4-week block-bootstrap 95\%% CI "
            r"$[%+.4f, %+.4f]$.}" % tuple(s["boot_ci95"]) + EOL]
    _write("regime", rows, "results/regime_hurst.json, git " + _sha("regime_hurst"))


def table_environment():
    """Table T-new4: compute environment. (M7)"""
    d = _load("environment")
    env = d.get("environment", d)
    rows = [r"%s & %s" % (k.replace("_", " ").capitalize(), v) + EOL
            for k, v in env.items()
            if not k.startswith("_") and isinstance(v, (str, int, float))]
    _write("environment", rows, "results/environment.json")


EMITTERS = [table_nconv, table_mcquality, table_arbitrage,
            table_regime, table_environment]

if __name__ == "__main__":
    only = sys.argv[1:]
    ok = skipped = 0
    for fn in EMITTERS:
        if only and not any(o in fn.__name__ for o in only):
            continue
        try:
            fn()
            ok += 1
        except FileNotFoundError:
            print("  SKIP %-18s no results JSON yet" % fn.__name__)
            skipped += 1
        except KeyError as e:
            print("  SKIP %-18s JSON present but missing key %s" % (fn.__name__, e))
            skipped += 1
    print("\n%d table(s) written, %d skipped." % (ok, skipped))
    if skipped:
        print("Skipped tables keep whatever the manuscript already has.")
