r"""
Emit LaTeX table bodies from results/*.json.
============================================

Companion to figures_paper.py. Together they close the hand-transcription loop
that produced defects C1-C7: until now every number reached the manuscript as
stdout -> a script docstring -> a LaTeX literal, with no link back to the run
that measured it.

Each emitter writes paper_cnsns/tables/<name>.tex containing ONLY the rows, so
the manuscript keeps its own caption, label and column spec and can be edited
freely without this script clobbering it. Include with \input{tables/<name>}.

A table whose JSON is missing is reported and skipped, never emitted from stale
numbers.
"""
import json, os, sys

OUT = os.path.join("paper_cnsns", "tables")
EOL = r" \\"          # LaTeX row terminator


def _load(name):
    """Return the payload; resultio.dump wraps it under "payload" with provenance."""
    with open(os.path.join("results", name + ".json")) as fh:
        d = json.load(fh)
    return d.get("payload", d)


def _sha(name):
    with open(os.path.join("results", name + ".json")) as fh:
        return json.load(fh).get("git_sha", "?")[:8]


def _write(name, rows, note):
    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, name + ".tex")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("%% GENERATED by make_tables.py -- do not edit by hand.\n")
        fh.write("%% source: " + note + "\n")
        fh.write("\n".join(rows) + "\n")
    print("  wrote " + path)


def table_nconv():
    """Table 2: dimension scaling of the forward operator.

    Solve- and lift-error from the seed sweep (J1); training time per n from the
    hparams n-sweep (same width/depth/n_col) when it exists, since the sweep
    itself does not time its runs.
    """
    d = _load("n_convergence")
    nseed = len(d["rows"][0].get("solves", [])) or "?"
    secs = {}
    try:
        secs = {q["n"]: q["train_seconds"] for q in _load("hparams")["n_sweep"]}
    except (FileNotFoundError, KeyError):
        pass
    rows = []
    for r_ in d["rows"]:
        t = ("$%.0f$" % secs[r_["n"]]) if r_["n"] in secs else "--"
        e = "%.1e" % (50.0 ** (r_["n"] + 1))
        mant, ex = e.split("e")
        rows.append(r"%-3d & $%.1f\pm%.1f$ & $%.1f$ & %s & $%s\times10^{%d}$" % (
            r_["n"], r_["solve_mean"], r_["solve_std"], r_["lift"], t, mant, int(ex)) + EOL)
    _write("nconv", rows, "results/n_convergence.json (%s seeds), git %s"
           % (nseed, _sha("n_convergence")))


def table_mcquality():
    """Table T-new1: is the Monte Carlo reference precise enough? (R1.2)

    Paired SE at the published 200k budget; the naive i.i.d. figure the code used
    to report, which overstates it; the SE at the 1M budget the revision adopts;
    the common-random-numbers bound on Euler bias at 400 steps; and the published
    solve-error after de-noising.
    """
    d = _load("mc_quality")
    by_n = {r["n"]: r for r in d["statistical"]}
    nan = float("nan")
    rows = []
    for h in d["headline"]:
        r = by_n.get(h["n"], {})
        # the statistical block stores SEs in price units; the table is in px bp
        rows.append(r"%-3d & $%.2f$ & $%.2f$ & $%.2f$ & $%.2f$ & $%.1f$ & $%.1f$" % (
            h["n"], 1e4 * r.get("rms_se_200k", nan),
            1e4 * r.get("rms_se_200k_naive", nan), 1e4 * r.get("rms_se_1m", nan),
            h["euler_bias_400_px_bp"], h["published"], h["denoised"]) + EOL)
    _write("mcquality", rows, "results/mc_quality.json, git " + _sha("mc_quality"))


def table_arbitrage():
    """Table T-new3: static-arbitrage counts on market, model and liquid core.

    The point is R1.6: if the filtered surface is arbitrage-free then the 496
    vol bp fit is a statement about the model, not about the data.
    """
    d = _load("arbitrage")
    rows = []
    for key, label in [("market", "Market surface"),
                       ("model", "Calibrated model surface"),
                       ("liquid_core", r"Liquid core ($|k|\le0.10$)")]:
        s = d.get(key)
        if not s or "butterfly" not in s:
            continue
        rows.append(r"%s & %d/%d & %d/%d & %d/%d & $%+.2f$" % (
            label,
            s["butterfly"]["n_violations"], s["butterfly"]["n_tested"],
            s["vertical"]["n_violations"], s["vertical"]["n_tested"],
            s["calendar"]["n_violations"], s["calendar"]["n_tested"],
            s["butterfly"]["worst_px_bp"]) + EOL)
    if not rows:
        raise KeyError("market/model/liquid_core")
    q = d["data_quality"]
    rows.append(r"\midrule")
    rows.append(r"\multicolumn{5}{@{}l}{%d raw instruments filtered to %d fitted "
                r"points: %d two-sided, %d mark-price fallback, %d zero volume.}"
                % (q["n_raw_instruments"], q["n_fitted"], q["n_two_sided"],
                   q["n_mark_fallback"], q["n_zero_volume"]) + EOL)
    _write("arbitrage", rows, "results/arbitrage.json, git " + _sha("arbitrage"))


def table_regime():
    """Table: option-implied parameters by market regime, pre- and post-ETF. (R1.5)

    One row per comparison from diagnose_regime_hurst.py: H from each warm start,
    rho and nu (the parameters the surface does identify), the fit itself, and
    which end of the H ridge each regime prefers.
    """
    d = _load("regime_hurst")
    s = d["summary"]
    # dp: parameters to 3 decimals, vol-bp quantities to 1 -- three decimals on a
    # basis-point figure both overflows the column and implies precision we do
    # not have (the weekly SDs are 45-84 vol bp).
    labels = [("H_canonical", r"$H$ (canon.\ start)", 3), ("H_wide", r"$H$ (wide start)", 3),
              ("rho_canonical", r"$\rho$", 3), ("nu_canonical", r"$\nu$", 3),
              ("fit_canonical", r"fit (vol\,bp)", 1),
              ("basin", r"basin gap (vol\,bp)", 1)]
    rows = []
    for key, lab, dp in labels:
        c = s.get(key)
        if not c:
            continue
        f = "%%.%df" % dp
        fmt = ("%s & $" + f + r"\pm" + f + "$ & $" + f + r"\pm" + f
               + "$ & $%+" + f[1:] + "$ & $[%+" + f[1:] + ", %+" + f[1:] + "]$ & %.3f")
        rows.append(fmt % (lab, c["pre_mean"], c["pre_sd"], c["post_mean"], c["post_sd"],
                           c["diff"], c["boot_ci95"][0], c["boot_ci95"][1], c["welch_p"]) + EOL)
    if not rows:
        raise KeyError("summary")
    b = s.get("basin")
    if b:
        rows.append(r"\midrule")
        rows.append(r"\multicolumn{6}{@{}l}{Weeks preferring the smoother-$H$ basin: "
                    r"%.0f\%% pre, %.0f\%% post; $n=%d$ and $%d$ weeks.}" % (
                        100 * b["frac_prefer_wide_pre"], 100 * b["frac_prefer_wide_post"],
                        b["n_pre"], b["n_post"]) + EOL)
    _write("regime", rows, "results/regime_hurst.json, git " + _sha("regime_hurst"))


def table_profile():
    """Table: profile likelihood in H -- the ridge. (M11)"""
    d = _load("calib_uncertainty")
    c = d["canonical"]
    rows = []
    for p in d["profile_H"]:
        q = p["params"]
        rows.append(r"$%.3f$ & $%.1f$ & $%.1f$ & $%.3f$ & $%+.3f$ & $%.3f$" % (
            p["fixed"], 1e4 * p["weighted"], p["unweighted_vol_bp"],
            q["nu"], q["rho"], q["lam"]) + EOL)
    # A footnote row wider than the columns stretches the whole tabular and pushes
    # the last column into the margin, so keep it short and put detail in the caption.
    rows.append(r"\midrule")
    rows.append(r"\multicolumn{6}{@{}l}{Best $H=%.3f$; 5\%% interval $[%.3f, %.3f]$.}" % (
        c["params"]["H"], d["interval_H"][0], d["interval_H"][1]) + EOL)
    _write("profile", rows, "results/calib_uncertainty.json, git " + _sha("calib_uncertainty"))


def table_risk():
    """Table: risk functionals for every vector the surface cannot tell apart. (R1.8)"""
    d = _load("risk_functionals")
    rows = []
    for r_ in d["rows"]:
        rows.append(r"%s & %s & $%.2f$ & $%+.2f$ & $%+.1f$" % (
            r_["source"], r_["tag"].replace("%", r"\%"), 100 * r_["varswap_vol"],
            100 * r_["rr25_vol"], r_["collar_px_bp"]) + EOL)
    s = d["summary"]
    if s["varswap_vol"]["ridge"]:
        rows.append(r"\midrule")
        rows.append(r"\multicolumn{5}{@{}l}{Range along the ridge (%d vectors): variance swap %.2f, "
                    r"risk reversal %.2f vol pts; collar %.1f px\,bp.}" % (
                        s["varswap_vol"]["ridge"]["n"], 100 * s["varswap_vol"]["ridge"]["range"],
                        100 * s["rr25_vol"]["ridge"]["range"], s["collar_px_bp"]["ridge"]["range"]) + EOL)
    _write("risk", rows, "results/risk_functionals.json, git " + _sha("risk_functionals"))


def table_liquid():
    """Table: liquid-core refit. (R1.6)"""
    d = _load("liquid_core")
    rows = []
    for label, w in d["windows"].items():
        tex = r"$|k|\le%.2f$" % float(label.split("<=")[1]) if label.startswith("|k|<=") else label
        for name, u in w["unrefitted"].items():
            rows.append(r"%s & %d & %s, no refit & $%.1f$ & $%.1f$ & -- & -- & --" % (
                tex, w["n_points"], name, u["weighted_vol_bp"], u["unweighted_vol_bp"]) + EOL)
            tex = ""                                     # print the window once
        for name, f in w["refitted"].items():
            p = f["params"]
            rows.append(r" & & refit from %s & $%.1f$ & $%.1f$ & $%.3f$ & $%+.3f$ & $%.3f$" % (
                name, f["weighted_vol_bp"], f["unweighted_vol_bp"], p["H"], p["rho"], p["nu"]) + EOL)
    _write("liquid", rows, "results/liquid_core.json, git " + _sha("liquid_core"))


def table_hparams():
    """Tables T-new5: architecture grid at n=4, and residual persistence across n. (M9, R1.3)"""
    d = _load("hparams")
    rows = [r"%d & %d & %d & $%.1f\pm%.1f$ & $%.2e$ & %.1f" % (
                q["width"], q["depth"], q["n_params"], q["solve_mean"], q["solve_sd"],
                q["residual_mean"], q["train_seconds"] / 60) + EOL
            for q in d["grid"]]
    _write("hparams_grid", rows, "results/hparams.json, git " + _sha("hparams"))
    s4, r4 = d["n_sweep"][0]["solve_mean"], d["n_sweep"][0]["residual_mean"]
    rows = [r"%d & $%.1f\pm%.1f$ & $%.2e$ & %.2f & %.2f" % (
                q["n"], q["solve_mean"], q["solve_sd"], q["residual_mean"],
                q["solve_mean"] / s4, q["residual_mean"] / r4) + EOL
            for q in d["n_sweep"]]
    _write("hparams_nsweep", rows, "results/hparams.json, git " + _sha("hparams"))
    rows = [r"%d & $%.1f\pm%.1f$ & $%.2e$ & %.1f" % (
                q["n_col"], q["solve_mean"], q["solve_sd"], q["residual_mean"],
                q["train_seconds"] / 60) + EOL
            for q in d["collocation"]]
    _write("hparams_colloc", rows, "results/hparams.json, git " + _sha("hparams"))


def table_n32():
    """Table: n=32 bias ablation. (R1.7)"""
    d = _load("n32_bias")
    rows = []
    for name, c in d["configs"].items():
        sw = c["signed_solve_iv_bp"]
        rows.append(r"%s & $%.1f\pm%.1f$ & $%+.0f$ & $%+.0f$ & $%+.0f$" % (
            name, c["solve_mean"], c["solve_std"], sw["OTMputs"], sw["ATM"], sw["OTMcalls"]) + EOL)
    e = d.get("euler_bias_row")
    if e:
        rows.append(r"\midrule")
        rows.append(r"\multicolumn{5}{@{}l}{Reference Euler bias at 400 steps: $%.2f$ px\,bp "
                    r"(finer grids price lower).}" % e["euler_bias_400_px_bp"] + EOL)
    _write("n32bias", rows, "results/n32_bias.json, git " + _sha("n32_bias"))


def table_surrogate():
    """Rows for the forward-operator comparison: the supervised surrogate. (R1.4)"""
    d = _load("surrogate")
    s = d["summary"]
    # columns: Operator & Offline cost & Exact pricer offline? & vs Fourier & vs lifted MC
    #          & Solve/lift split & Differentiable   (see tab:operators in the manuscript)
    rows = [r"Supervised surrogate (MLP) & %.0f min $+$ %.0f s & yes & $%.1f\pm%.1f$ & -- & no & yes" % (
                d["label_seconds"] / 60, s["train_seconds_mean"], s["test_rmse_mean"],
                s["test_rmse_sd"]) + EOL,
            r"\multicolumn{7}{@{}l}{\quad in the rough / high-$\nu$ corner: "
            r"$%.1f\pm%.1f$ vol\,bp on %d test vectors.}" % (
                s["corner_rmse_mean"], s["corner_rmse_sd"], d["runs"][0]["n_corner"]) + EOL]
    _write("surrogate", rows, "results/surrogate.json (%d labelled vectors), git %s"
           % (d["n_labelled"], _sha("surrogate")))


def table_calib():
    """Table: three routes to the inverse problem, both parametric boxes. (M3, M6, M-res)"""
    d = _load("param_boxes")
    F = d["from_scratch"]
    rows = [r"True-forward-model loop, from scratch & $%.1f$ & $%.0f$ & $%d$" % (
                F["rmse_vol_bp"], F["seconds"], F["evals"]) + EOL]
    for box, lab in (("default", "original box"), ("wide", "widened box")):
        b = d["per_box"][box]
        rows.append(r"AI-only (single-shot), %s & $%.0f\pm%.0f$ & ${\sim}2$ & $0$" % (
            lab, b["ai_only_rmse"]["mean"], b["ai_only_rmse"]["sd"]) + EOL)
        rows.append(r"Hybrid (AI warm start, true-model polish), %s & $%.1f\pm%.1f$ & $%.0f$ & $%.0f\pm%.0f$" % (
            lab, b["hybrid_rmse"]["mean"], b["hybrid_rmse"]["sd"], b["hybrid_seconds"],
            b["hybrid_evals"]["mean"], b["hybrid_evals"]["sd"]) + EOL)
    _write("calib", rows, "results/param_boxes.json, git " + _sha("param_boxes"))


def table_environment():
    """Table T-new4: compute environment. (M7)"""
    d = _load("environment")
    env = d.get("environment", d)
    rows = [r"%s & %s" % (k.replace("_", " ").capitalize(), v) + EOL
            for k, v in env.items()
            if not k.startswith("_") and isinstance(v, (str, int, float))]
    _write("environment", rows, "results/environment.json")


EMITTERS = [table_nconv, table_mcquality, table_arbitrage,
            table_regime, table_profile, table_risk, table_liquid,
            table_hparams, table_n32, table_surrogate, table_calib, table_environment]

if __name__ == "__main__":
    only = sys.argv[1:]
    ok = skipped = 0
    for fn in EMITTERS:
        if only and not any(o in fn.__name__ for o in only):
            continue
        try:
            fn()
            ok += 1
        except FileNotFoundError:
            print("  SKIP %-18s no results JSON yet" % fn.__name__)
            skipped += 1
        except KeyError as e:
            print("  SKIP %-18s JSON present but missing key %s" % (fn.__name__, e))
            skipped += 1
    print("\n%d table(s) written, %d skipped." % (ok, skipped))
    if skipped:
        print("Skipped tables keep whatever the manuscript already has.")
